version: '3'

services:
  express-server:
    build: ./server
    ports:
      - "${EXPRESS_PORT}:3001"
    depends_on:
      - db

  nextjs-app:
    build: ./chatbot
    ports:
      - "3000:3000"
    depends_on:
      - express-server

  db:
    image: mongo:latest
    env_file:
      - ./server/.env
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data: