version: '3'

services:
  express-server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db

  nextjs-app:
    build: ./chatbot
    ports:
      - "3000:3000"
    depends_on:
      - express-server

  db:
    image: mongo:latest
    volumes:
      - db-data:/data/db

volumes:
  db-data: