# This file stores sensitive configuration data (API keys)
# IMPORTANT: Replace the placeholder values with your actual API keys
# For production, use kubectl create secret or a secure secret management solution
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secrets
  namespace: chatbot-app
type: Opaque
data:
  # Base64 encoded values (use: echo -n "your-api-key" | base64)
  OPEN_AI_KEY: "<your-openai-key>"
  GOOGLE_API_KEY: "<your-google-api-key>" 