# This file defines the Next.js frontend deployment for Kubernetes/Minikube
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot # The name of the deployment
spec:
  replicas: 1 # Only one frontend pod for local development
  selector:
    matchLabels:
      app: chatbot # Label to match pods managed by this deployment
  template:
    metadata:
      labels:
        app: chatbot # Label for the pod
    spec:
      containers:
        - name: chatbot
          image: chatbot:latest # Use the locally built Docker image
          imagePullPolicy: Never # Don't try to pull from a registry; use local image
          ports:
            - containerPort: 3000 # Port the Next.js app listens on
